apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: pedialink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: oumaymahannachi/auth-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/pedialink"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: pedialink
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
