apiVersion: v1
kind: Service
metadata:
  name: dossiermedical-service
  namespace: pedialink
spec:
  ports:
    - port: 8087
  selector:
    app: dossiermedical-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dossiermedical-service
  namespace: pedialink
spec:
  selector:
    matchLabels:
      app: dossiermedical-service
  template:
    metadata:
      labels:
        app: dossiermedical-service
    spec:
      containers:
      - name: dossiermedical-service
        image: localhost:5005/dossiermedical-service:latest
        ports:
          - containerPort: 8087
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/pedialink"
