apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: pedialink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: oumaymahannachi/config-server:latest
        ports:
        - containerPort: 8888
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: pedialink
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prescription-service
  namespace: pedialink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prescription-service
  template:
    metadata:
      labels:
        app: prescription-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8082"
    spec:
      containers:
      - name: prescription-service
        image: oumaymahannachi/prescription-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://mongodb:27017/pedialink"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-server:8888"
---
apiVersion: v1
kind: Service
metadata:
  name: prescription-service
  namespace: pedialink
spec:
  selector:
    app: prescription-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: treatment-service
  namespace: pedialink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: treatment-service
  template:
    metadata:
      labels:
        app: treatment-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8083"
    spec:
      containers:
      - name: treatment-service
        image: oumaymahannachi/treatment-service:latest
        ports:
        - containerPort: 8083
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://mongodb:27017/pedialink"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-server:8888"
---
apiVersion: v1
kind: Service
metadata:
  name: treatment-service
  namespace: pedialink
spec:
  selector:
    app: treatment-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: treatment-monitoring-service
  namespace: pedialink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: treatment-monitoring-service
  template:
    metadata:
      labels:
        app: treatment-monitoring-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8084"
    spec:
      containers:
      - name: treatment-monitoring-service
        image: oumaymahannachi/treatment-monitoring-service:latest
        ports:
        - containerPort: 8084
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://mongodb:27017/pedialink"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-server:8888"
---
apiVersion: v1
kind: Service
metadata:
  name: treatment-monitoring-service
  namespace: pedialink
spec:
  selector:
    app: treatment-monitoring-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-results-service
  namespace: pedialink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-results-service
  template:
    metadata:
      labels:
        app: lab-results-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8085"
    spec:
      containers:
      - name: lab-results-service
        image: oumaymahannachi/lab-results-service:latest
        ports:
        - containerPort: 8085
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://mongodb:27017/pedialink"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-server:8888"
---
apiVersion: v1
kind: Service
metadata:
  name: lab-results-service
  namespace: pedialink
spec:
  selector:
    app: lab-results-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-service
  namespace: pedialink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-service
  template:
    metadata:
      labels:
        app: messaging-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8086"
    spec:
      containers:
      - name: messaging-service
        image: oumaymahannachi/messaging-service:latest
        ports:
        - containerPort: 8086
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://mongodb:27017/pedialink"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-server:8888"
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-service
  namespace: pedialink
spec:
  selector:
    app: messaging-service
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: ClusterIP
