server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://PediaLink:PediaLink@pedialink.0d8a5qd.mongodb.net/pedialink?retryWrites=true&w=majority}
  datasource:
    url: jdbc:h2:file:./data/auth-backup;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

app:
  jwt:
    secret: PediaLinkSuperSecretKeyForJwtToken2024MustBeAtLeast256BitsLong!!
    expiration: 86400000
  otp:
    expiration-minutes: 10
  cors:
    allowed-origins: http://localhost:4200

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

logging:
  level:
    tn.pedialink.auth: DEBUG
    org.springframework.security: DEBUG
