apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: pedialink
spec:
  ports:
    - port: 80
      nodePort: 30042
  selector:
    app: frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pedialink
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: localhost:5005/pedialink-frontend:latest
        ports:
          - containerPort: 80
