apiVersion: v1
kind: Namespace
metadata:
  name: pedialink
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: pedialink
spec:
  ports:
    - port: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: pedialink
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
          - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        emptyDir: {} # Pour la démo, sinon utiliser un PersistentVolume
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: pedialink
spec:
  ports:
    - port: 8761
  selector:
    app: eureka-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: pedialink
spec:
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: oumaymahannachi/eureka-server:latest
        ports:
          - containerPort: 8761
