management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: ${server.port} # Garder le même port pour actuator

# Forcer la désactivation de la sécurité sur les endpoints actuator si possible via properties
spring:
  security:
    user:
      name: user
      password: password

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/pedialink
