spring:
  data:
    mongodb:
      database: pedialink
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
