global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pedialink-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: 
        - 'pedialink-gateway:8080'
        - 'pedialink-auth:8081'
        - 'pedialink-dossiermedical:8087'
        - 'pedialink-prescription:8084'
        - 'pedialink-treatment:8085'
        - 'pedialink-treatment-monitoring:8082'
        - 'pedialink-lab-results:8089'
        - 'pedialink-messaging:8090'
